### ISSUE TITLE
About Stacking on Mobile

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/EddieHubLive#102]
### Description

The about button stacks into the event cards and the modal has not been configured for mobile use.  

Related to #101

**Comment by amandamartin-dev** [comment]
@sudhanshutech here is the modal issue

**Comment by sudhanshutech** [comment]
Sure, i am on it

**Comment by amandamartin-dev** [comment]
Amazing! Thank you so much for the contributions. If you notice anythign else while you are working that could be improved feel free to submit more issues for consideration

**Comment by sudhanshutech** [comment]
@amandamartin-dev bug has been resolved
