### ISSUE TITLE
CSS review - remove unused classes

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/EddieHubLive#104]
### What would you like to share?

I believe there is some extra css in the nav bar and it's elements.  This issue is to review tailwind classes and remove anything unnecessary

For anyone taking on this issue, remember to check the style at all viewport sizes

**Comment by 07jhashubham** [comment]
I am eager to take on this challenge and contribute to the project's success. 

I understand the importance of this task, and I am committed to delivering the best possible results.

**Comment by yuviS003** [comment]
Please assign this issue to me

**Comment by 8rxn** [comment]
Hello, I would like to work on this issue. I have recently worked on various projects using Tailwind. Could you assign it to me.

**Comment by amandamartin-dev** [comment]
Hello all! Sorry for the delay, I will assign the first person who asked and go from there if they are not able to complete it.  Thank you all for your willingness to contribute!

**Comment by amandamartin-dev** [comment]
> Can I work on this. It looks familiar for me..

Assigned. If you are no longer interested in this issue, please let me know
