### ISSUE TITLE
[FEATURE] Use mapbox's api for the world map

### ISSUE THREAD

**Issue by GauravBurande** [EddieHubCommunity/EddieHubLive#109]
### Description

I think using mapbox's api for rendering the world map will increase the UX.
The map provided by mapbox's API using mapbox-gl library has better UI and UX.
Have a look below
### Screenshots

https://user-images.githubusercontent.com/100035026/221805337-9c6f381c-638a-40c8-98a9-a7e72029179d.webm

**Comment by amandamartin-dev** [comment]
Hello! Thank you for offering this suggestion.  My understanding about Mapbox is that it is not free.  Are you able to investigate this?  

it is also not an open source product and in the spirit of this project, I think it makes sense to continue with open sources tools unless there is a compelling reason to switch. So after potential costs, in terms of UI/UX can you provide specific points to this idea?


Thank you so much for the idea and research. We can discuss more.

**Comment by GauravBurande** [comment]
> Hello! Thank you for offering this suggestion. My understanding about Mapbox is that it is not free. Are you able to investigate this?
> 
> it is also not an open source product and in the spirit of this project, I think it makes sense to continue with open sources tools unless there is a compelling reason to switch. So after potential costs, in terms of UI/UX can you provide specific points to this idea?
> 
> Thank you so much for the idea and research. We can discuss more.

Yes it's both not free and open source, I'll try to find other open source alternatives.

**Comment by amandamartin-dev** [comment]
> Yes it's both not free and open source, I'll try to find other open source alternatives.

I only have it locally but I've been working with CesiumJS on a prototype for a globe view.  My issue with this one so far though is that the UI is not very pretty for the globe controls and doesn't seem to be that we can change that.  But feel free to check it out if you want as well. Maybe I missed something!
