### ISSUE TITLE
Relative date time on the right sidebar in the UI

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/EddieHubLive#13]
![image](https://user-images.githubusercontent.com/150512/88559686-0a190280-d025-11ea-81f2-62ab0f9fc727.png)

**Comment by amandamartin-dev** [comment]
@eddiejaoude looking through some of these older tickets to close if any are no longer relevant.  This screenshot looks to perhaps show an older version of the app or would you say this is still a relevant issue?

**Comment by eddiejaoude** [comment]
You are correct @amandamartin-dev this was for a previous version with different technology (I think it was Firebase). I will close
