### ISSUE TITLE
Markers overlap issue

### ISSUE THREAD

**Issue by alrifay** [EddieHubCommunity/EddieHubLive#16]
Overlapped marker should be replaced with one marker contains total count.
For [example](https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html):
![image](https://user-images.githubusercontent.com/19517534/88610695-9eb44c80-d087-11ea-86af-618c0768c63d.png)

I found this leaflet plugin that does that [Leaflet.markercluster
](https://github.com/Leaflet/Leaflet.markercluster)

**Comment by amandamartin-dev** [comment]
I can take this on next!

**Comment by amandamartin-dev** [comment]
Created some test data locally and poking around a bit. 

It seems that react-leaflet (currently in the project) does not have an implementation of Marker cluster in it.  I found 2 different wrapper libraries that could work.  Lmk if there are any thoughts about which would be better (or neither)

https://github.com/giovanesantossilva/react-leaflet-muster
https://github.com/akursat/react-leaflet-cluster
