### ISSUE TITLE
Users updated avatars doesn't appear on the map

### ISSUE THREAD

**Issue by alrifay** [EddieHubCommunity/EddieHubLive#17]
I think this issue happens because you are using old avatar url from Firestore.
https://github.com/EddieJaoudeCommunity/EddieBotMap/blob/584f682704fc50a7071b237b83f81e9183c8892f/src/app/app.component.ts#L71

Does discord provide an event for updated avatars? so you can save the new url.🤔

Or maybe ask users to update their bio after changing the avatar to save the new url. 😁

**Comment by amandamartin-dev** [comment]
@eddiejaoude I noticed this issue and others mention discord as having a connection to create map events.  Can you let me know if this is still the case or if the connection is only through the github actions.

**Comment by eddiejaoude** [comment]
I think back then we had events from Discord, but now it is only events from GitHub - so I will close this 👍
