### ISSUE TITLE
Hide GitHub Action events 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubLive#30]
### Description

Filter out these 3 events

- workflowRun
- checksuite
- checkRun

**Comment by Chris-N** [comment]
Happy to find a good solid first issue. So where can I get more information/understanding the GitHub Action events. I'm also trying to understand where can I find these 3 events you want filtered out at? 🤔

**Comment by eddiejaoude** [comment]
Great questions Chris! I think we want to stop those Action events being added to the list and map on this line https://github.com/EddieHubCommunity/EddieHubLive/blob/main/src/App.js#L12

Maybe having something like this (untested code)

```js
const ignoreEvents = ['workflowRun', 'checksuite', 'checkRun'];
if (ignoreEvents.includes(data.event) {
   return;
}
```

That way those 3 events are not displayed on the list or map.

**Comment by Chris-N** [comment]
Thanks for the context! At the same time with this comment I'm testing out the GitHub webhook event to fire from the suggestion you left on discord until Naomi writes up a doc procedure to simulate this with `curl...` command.

**Comment by Chris-N** [comment]
Is there a defined shape of the data the comes through from the webhook somewhere?

**Comment by eddiejaoude** [comment]
Yes there are examples in the GitHub docs here https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
