### ISSUE TITLE
Only add user to map once

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubLive#31]
### Description

Currently the user is added to the map multiple times (only seen once), this will get slow

Maybe check if the user is on the map already, if so do nothing

**Comment by brijeshsoni1300** [comment]
![image](https://user-images.githubusercontent.com/51873202/178214222-6c1f2fc1-118b-4543-a4ad-04e799ef8d6c.png)
so we are considering this as a same?
not sure but is soln like?
changing
```setEvents([...events,data])``` to ```setEvents([...new Set([...events, data])])``` work?
so it will remove those above duplicate entries

**Comment by brijeshsoni1300** [comment]
okay so,
1. instead   ```<Map events={events} />```
could we pass   ```<Map events={[...new Set(events)]} />``` to remove duplicate entries?
or
2.  could we create another list of users which is a set of users and update that list every time we get new data and add user to that list if not exist already?
or still, I m not getting it properly?

**Comment by eddiejaoude** [comment]
oh interesting! I like your idea `<Map events={[...new Set(events)]} />`, let's try that 👍 

You got it correct, great work @brijeshsoni1300  🔥

**Comment by eddiejaoude** [comment]
The issue still remains 

<img width="1266" alt="Screenshot 2022-07-11 at 19 49 45" src="https://user-images.githubusercontent.com/624760/178337274-2f475ea0-299c-424c-a822-fa12d9fd5aff.png">

**Comment by eddiejaoude** [comment]
Testing this locally with...

```js
      if (!uniqueUsers.includes(data.githubUsername._id)) {
        setUniqueUsers([...uniqueUsers, data]);
      }
```

**Comment by brijeshsoni1300** [comment]
what if we have one function which filters our list to have only one entry of object per GitHub URL
```
  function removeDuplicateUsersFromEvents(){
    let uniqueEvents = [];
    events.forEach(event => {
      if(!uniqueEvents.some(uniqueEvent => uniqueEvent.githubUserURL === event.githubUserURL)){
        uniqueEvents.push(event);
      }
    }
    );
    console.log(events)
    console.log("uniqueEvents"+uniqueEvents)
    return uniqueEvents;
  }
```

and then passing it to Map
```<Map events={removeDuplicateUsersFromEvents()} />```

well I checked it locally, it's filtering for your URL
there were 23 entries in the events list
but one entry after removing dups in uniqueEvents list

**Comment by brijeshsoni1300** [comment]
> Testing this locally with...
> 
> ```js
> if (!uniqueUsers.includes(data.githubUsername._id)) {
>    setUniqueUsers([...uniqueUsers, data]);
> }
> ```

actually in those List of objects we have repeated ids so it will cause dups again
![image](https://user-images.githubusercontent.com/51873202/178410996-0bfd4412-b60a-42ea-834d-03e89a40a3c7.png)

**Comment by brijeshsoni1300** [comment]
> Testing this locally with...
> 
> ```js
> if (
>    !uniqueUsers.find(
>       (user) => user.githubUsername._id === data.githubUsername._id
>    )
> ) {
>    setUniqueUsers([...uniqueUsers, data]);
> }
> ```

okay got it, we are filtering it using Github id so that will be the same for the same user 
let me try this
