### ISSUE TITLE
[FEATURE] Display deployed version

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubLive#44]
### Description

It would be useful to know what version is deployed, similar to our other apps

**Comment by jalezi** [comment]
@eddiejaoude where would you like version to be displayed? On map?

**Comment by eddiejaoude** [comment]
Some where on the top or bottom, similar to our LinkFree project https://linkfree.eddiehub.io

**Comment by jalezi** [comment]
like this or i have to put in the header/footer?
![Screenshot 2022-10-09 at 20 57 01](https://user-images.githubusercontent.com/44704999/194774645-738c2e83-2332-44c7-ac54-8287d4803f34.png)

**Comment by eddiejaoude** [comment]
That looks good 👍, we can always move it around later on if needed

**Comment by jalezi** [comment]
uh, I have different prettier settings 😢 . What should I do?

**Comment by eddiejaoude** [comment]
we probably need to fix it so the project has settings, but for now, just change the minimum amount of lines
