### ISSUE TITLE
Websockets bug

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/EddieHubLive#51]
### Description

In checking live.eddiehub.io (production, not locally) I noticed no data in the panel.  

In inspection of the network although the websocket connection is 101 as expected, it appears that no data is being transferred.  

May be a configuration issue with websockets. See screenshots from the network tab.

Tested in chrome and firefox (latest) on a mac 12.5.1

### Screenshots

![packets](https://user-images.githubusercontent.com/97615019/203411610-f3019362-1bcf-41d3-95b1-086bf7aeb3ea.jpg)

![eddiehublive_bug](https://user-images.githubusercontent.com/97615019/203411640-e2b97e5c-16e6-448c-bbd0-3ced75c58fba.jpg)

**Comment by amandamartin-dev** [comment]
Tested again after adding this issue out of curiosity and now I do see a "github event" in the websocket traffic, but something is still amiss and no data is displayed.

![second test](https://user-images.githubusercontent.com/97615019/203412710-e5365f73-76fb-436c-87a4-1a91e253afa7.jpg)

**Comment by eddiejaoude** [comment]
Oh yes, I forgot about this, you need to opt in to have your event data for the EddieHub Org displayed

I think we need to add that to the README

Issue to opt into the webhook event being displayed
https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=EddieHub-API-add&template=add-api-user.yml&title=Please+add+me+to+the+EddieHub+API

**Comment by amandamartin-dev** [comment]
@eddiejaoude Ah! That makes sense.  I will close this ticket as not a bug

**Comment by amandamartin-dev** [comment]
closed, not a bug.
