### ISSUE TITLE
[DOCS] Add instructions on how to get data to display

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/EddieHubLive#52]
### Description

Add instructions for submitting to the EddieHub API and how to initiate new data to fill the side panel. 

Info - refine for clarity and tone:

Submit a request here to be added to the API: https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=EddieHub-API-add&template=add-api-user.yml&title=Please+add+me+to+the+EddieHub+API

After that, open or comment on an issue in the EddieHubLive project to create an entry, edit your comment to create multiple entries

do not keep adding new comments to create data, this will create spam.  Editing your existing comment should work for testing purposes.

**Comment by eddiejaoude** [comment]
Thanks Amanda 💯

**Comment by amandamartin-dev** [comment]
I can take this next, but quick question  - for a docs change, is it the same as code? Would I create a branch, etc etc?  Also, if these instructions are listed out somewhere already, please link me!

**Comment by eddiejaoude** [comment]
Yes please 👍 

- yep it is the same as code changes 
- currently everything is in the README, when it grows bigger we can look to move to a `docs` folder and include it in the app
