### ISSUE TITLE
[BUG] Missing a license

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/EddieHubLive#59]
### Description

We should add a license to this repository. This way, people will know what and what not they can do with this repository, permissions, notices, etc.. I suggest using the [**MIT license**](https://mit-license.org), however, we can use any other one as well.

### Additional information

I believe we should ask all the contributors if they agree to license the repository under a certain license (not 100% sure about that, though).

**Comment by Panquesito7** [comment]
@eddiejaoude.

**Comment by eddiejaoude** [comment]
Sorry I missed this, I think we use MiT across EddieHub project

**Comment by amandamartin-dev** [comment]
Thank you Eddie! Did you want to implement @Panquesito7 ?

**Comment by Panquesito7** [comment]
> Thank you Eddie! Did you want to implement @Panquesito7 ?

Sure, I could make a PR if wanted. 🙂

**Comment by amandamartin-dev** [comment]
All yours. Thank you!!
