### ISSUE TITLE
[FEATURE] Zoom to person for 10s

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubLive#66]
### Description

When a new event comes in, it would be great to zoom in to the map a bit so the persons pin can be seen better. Then after a certain time, zoom back out to show the whole map again

**Comment by amandamartin-dev** [comment]
@eddiejaoude oh this is interesting! When you are live what is the pace of new users generally?  Just thinking if it's quick that the map bouncing around could be visually annoying if it's back to back but i also like this idea as it welcomes new folks to the map/stream.

Another idea (would only work on desktop) is to keep the map bounds as large as all the points and "bounce" a new marker maybe with a temporary wave emoji over the pic.  This however would be complicated if there were enough points close together that marker cluster is initiated.

**Comment by eddiejaoude** [comment]
Thank you Amanda for thinking of various scenarios. I think this would mostly be used on the desktop, although I still struggle with having it on the screen while having other windows open - so a smaller view port would help

I guess I am keen to try to highlight new contributions that just happened, to encourage more people to add value and contribute - I am open to ideas on how to do this

**Comment by amandamartin-dev** [comment]
Realized while playing with this that we are passing all unique events to the map component on each new event.  There is no indication of if the event is a new to the map user as we are not storing a map marker state anywhere.  Can go one of two ways:
1. zoom to each new event that comes in regardless of if the contributor is new to the map and create a secondary ticket for solving map state to only highlight new to the map in the future
2. solve the state issue now along with the zoom to as defined by the ticket

I'm leaning towards 1 just for the sake of dividing up the work should anyone else want to jump in and contribute

**Comment by eddiejaoude** [comment]
Yep, point 1 sounds better to me also 👍 plus it might be fun doing it for every event - we can try this and then see if it needs changing
