### ISSUE TITLE
vertical overflow, there's a scrollbar on screen

### ISSUE THREAD

**Issue by Aadarsh805** [EddieHubCommunity/EddieHubLive#79]
### Description

I'm not sure if it's meant to have a scrollbar, it it's intentional, feel free to close the issue
I think it shouldn't as the map can zoom in and zoom out and the location sidebar can have a separate vertical scroll

### Screenshots

![image](https://user-images.githubusercontent.com/95094057/207736205-c6a7a476-0b05-42b0-91f4-9a25ee752b61.png)

**Comment by amandamartin-dev** [comment]
Hey @Aadarsh805 thank you for bringing this up! I am not seeing the same behavior in my environment.  Can you provide some more information that will help recreate this bug?

**Comment by Aadarsh805** [comment]
> Hey @Aadarsh805 thank you for bringing this up! I am not seeing the same behavior in my environment. Can you provide some more information that will help recreate this bug?

I just simply opened the link and this is how it shows, 
I'm on a 15'6 screen

**Comment by amandamartin-dev** [comment]
I played around a little more and I can se this behavior sometimes when I open in Safari or Firefox, but never in chrome.  Do you think it may be a cross-browser issue? Also, did you want to work on this? I am happy to assign it to you if you like

**Comment by Aadarsh805** [comment]
> I played around a little more and I can se this behavior sometimes when I open in Safari or Firefox, but never in chrome. Do you think it may be a cross-browser issue? Also, did you want to work on this? I am happy to assign it to you if you like

Yeah sure assign me, I'll look into it

**Comment by joshi-omkar** [comment]
Hello @amandamartin-dev if Aadarsh805 is not working on this bug, should i continue in this bug?

**Comment by amandamartin-dev** [comment]
@joshi-omkar sure! you are welcome to work on this.  thank you for contributing

**Comment by Aadarsh805** [comment]
@joshi-omkar hey, are you on it, or can I make a pr

**Comment by Aadarsh805** [comment]
@joshi-omkar If you would like some help, feel free to ask

**Comment by amandamartin-dev** [comment]
@Aadarsh805 I think it is okay to modify this if you like.  Multiple folks can work on an issue. @joshi-omkar let us know if you are still working or would like to collaborate with @Aadarsh805

**Comment by amandamartin-dev** [comment]
Hey @Aadarsh805  and @joshi-omkar I went ahead and pushed a change for this, feel free to take a look and offer a PR review then I will merge.  Appreciate calling attention to this issue and the collaboration. Thanks!
