### ISSUE TITLE
UI is not responsive

### ISSUE THREAD

**Issue by joshi-omkar** [EddieHubCommunity/EddieHubLive#88]
### Description

UI is not responsive, the event-card and About is not responsive.

### Screenshots

![image](https://user-images.githubusercontent.com/64478933/209361310-5486eab8-08b0-4acb-a662-8aebb0e37cf4.png)

**Comment by amandamartin-dev** [comment]
Thanks for reporting @joshi-omkar 

Do you have a UI proposal for the way this app should look at different sizes? If so, add some screenshots and we can work on the design ideas together

**Comment by gauravsahu21** [comment]
Hey @joshi-omkar I want to work on this issue

**Comment by amandamartin-dev** [comment]
Hi @gauravsahu21 you are welcome to start working on this if you like.  I will assign you

**Comment by amandamartin-dev** [comment]
Hi @gauravsahu21 just checking in to see if you are working on this issue and would like some more time or if I should open up so someone else can take it

**Comment by gauravsahu21** [comment]
hi @amandamartin-dev I am quite busy with something so please assign someone

**Comment by amandamartin-dev** [comment]
@gauravsahu21 no problem at all! I will unassign.  Feel free to check back later if you are interested in the future. Good luck with your projects!

**Comment by sudhanshutech** [comment]
is someone is working on this issue?

**Comment by amandamartin-dev** [comment]
> is someone is working on this issue?

No! Would you. like to?

**Comment by sudhanshutech** [comment]
> > is someone is working on this issue?
> 
> No! Would you. like to?

yes I would like to work on this issue

**Comment by amandamartin-dev** [comment]
All yours! Thanks for contributing

**Comment by sudhanshutech** [comment]
I made a style folder in src to make it responsive is it valid or should it have to be in the same file without making any additional files?
Can you suggest?

**Comment by amandamartin-dev** [comment]
Hi! This project is using Tailwind so in general you will style inline with tailwind classes. If you need another example of tailwind outside of this project, checkout linkfree
