### ISSUE TITLE
[FEATURE] Popup Improvement

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/EddieHubLive#97]
### Description

This issue is to review and add useful information to the map markers

Current map marker popup:
![screenshot of a round image of amanda marking. location on leaflet map with a popup open](https://user-images.githubusercontent.com/97615019/210882308-1a7a2d3c-f08d-4fa5-a7a6-12e7994bbd40.jpg)

**Comment by ScottDeev** [comment]
I will love to work on this but I have a little problem. When I ran the repo on my local machine this is what I get. There's no data displaying
![Screenshot (344)](https://user-images.githubusercontent.com/99127718/211537288-c00eb04a-7ea3-4e11-8f1c-27c4a4219109.png)

**Comment by eddiejaoude** [comment]
Hey @ScottDeev you need to do a few steps first to get data displayed, you can read about more about it here https://github.com/EddieHubCommunity/EddieHubLive#getting-started

**Comment by ScottDeev** [comment]
Alright @eddiejaoude. I will go through it and get myself set up. Thank you for the help always!

**Comment by eddiejaoude** [comment]
@ScottDeev I have assigned it to you 👍

**Comment by ScottDeev** [comment]
> @ScottDeev I have assigned it to you 👍

Alright!.
