### ISSUE TITLE
[FEATURE] UI Improvement - Add Scollbar to Events List

### ISSUE THREAD

**Issue by FozanGardezi** [EddieHubCommunity/EddieHubLive#99]
### Description

When the events list overflows, the scrollbar is added to the parent element of the events list and the map, which also expands the map.

Proposed UI Update:
When the events list overflows the scrollbar should only be added to it. 
I am also attaching the screenshot of the update I propose

### Screenshots

![Screenshot from 2023-01-17 21-57-54](https://user-images.githubusercontent.com/29943792/212963172-70f15e33-564b-4629-a859-d647cb95f83a.png)

**Comment by amandamartin-dev** [comment]
@FozanGardezi great idea! Thank you for the contribution. Would you like to work on this as well?

**Comment by amandamartin-dev** [comment]
Amazing! I will check it later once it's ready.
